version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: assets/webpack/
    target-branch: dev
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
