version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - containedctx # We do store contexts in some cases.
    - cyclop # Too opinionated.
    - gocognit # Too opinionated.
    - depguard # No need for dependency white/blacklisting.
    - exhaustruct # Too opinionated.
    - forbidigo # Too opinionated.
    - forcetypeassert # Too opinionated.
    - funcorder # Too opinionated.
    - funlen # Too opinionated.
    - gochecknoinits # We do use init functions.
    - gomoddirectives # We do local replacements.
    - mnd # Too opinionated.
    - nestif # Too opinionated.
    - nlreturn # Too opinionated.
    - noinlineerr # Too opinionated.
    - promlinter # Too opinionated.
    - tagalign # Too opinionated.
    - varnamelen # Too opinionated.
    - wsl # Too opinionated.
    - wsl_v5 # Too opinionated.
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
