inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "{{.Mock}}{{.InterfaceName | firstUpper}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
all: True
with-expecter: False
packages:
  allenta.com/varnishmon:
    config:
      recursive: True
