FROM docker.io/rockylinux/rockylinux:8.10.20240528-ubi

ARG GO_VERSION

ENV FPM_VERSION 1.11.0

RUN yum install -y \
        cmake3 \
        curl \
        gcc-c++ \
        git \
        make \
        rpm-build \
        ruby \
        ruby-devel \
        tar \
    && yum clean all

RUN ARCHITECTURE=$(uname -m) \
    && case $ARCHITECTURE in \
            x86_64)  ARCHITECTURE='amd64' ;; \
            aarch64) ARCHITECTURE='arm64' ;; \
            *)       echo "unknown architecture: $ARCHITECTURE" && exit 1 ;; \
        esac \
    && curl -L -s curl -L -s https://go.dev/dl/go${GO_VERSION}.linux-${ARCHITECTURE}.tar.gz | tar xvfz - -C /usr/local

# For RHEL 8 pre-installing 'dotenv' 2.8.1 (required by 'pleaserun') is not
# enough: 'gem' will still try to install a newer version of 'dotenv' when
# installing 'fpm' / 'pleaserun'. That will fail because of the Ruby version.
# This is a -hopefully temporary- dirty workaround. The same happens with 'ffi'
# 1.16.3, required by 'fpm'.
# See: https://github.com/jordansissel/fpm/issues/2048#issuecomment-1972196104.
RUN gem install dotenv -v 2.8.1 \
    && gem install ffi -v 1.16.3 \
    && gem install fpm -v ${FPM_VERSION} --minimal-deps --conservative --force \
    && gem uninstall dotenv -v '>2.8.1' \
    && gem uninstall ffi -v '>1.16.3' \
    && gem cleanup
