FROM docker.io/ubuntu:jammy-20260113

ARG GO_VERSION

ENV FPM_VERSION 1.17.0

ENV DEBIAN_FRONTEND noninteractive

RUN apt update \
    && apt install -y \
        curl \
        g++ \
        git \
        make \
        ruby \
        ruby-dev \
        tar \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L -s https://go.dev/dl/go${GO_VERSION}.linux-$(dpkg --print-architecture).tar.gz | tar xvfz - -C /usr/local

RUN gem install fpm -v ${FPM_VERSION} \
    && gem cleanup
