FROM docker.io/rockylinux/rockylinux:8.10.20240528-ubi

ARG GO_VERSION

ENV FPM_VERSION 1.11.0

RUN yum install -y \
        cmake3 \
        curl \
        gcc-c++ \
        git \
        make \
        rpm-build \
        ruby \
        ruby-devel \
        tar \
    && yum clean all

RUN ARCHITECTURE=$(uname -m) \
    && case $ARCHITECTURE in \
            x86_64)  ARCHITECTURE='amd64' ;; \
            aarch64) ARCHITECTURE='arm64' ;; \
            *)       echo "unknown architecture: $ARCHITECTURE" && exit 1 ;; \
        esac \
    && curl -L -s curl -L -s https://go.dev/dl/go${GO_VERSION}.linux-${ARCHITECTURE}.tar.gz | tar xvfz - -C /usr/local

# In this version of 'fpm' there's an unpinned dependency to 'ffi', which would
# lead to an installation of a version that would require Ruby 3.x and that's a
# problem in RHEL 8. Sadly, in RHEL 8 pre-installing gems is not enough: 'gem'
# will still install newer versions when required by other unpinned dependencies,
# so we must clean them up afterwards (see:
# https://github.com/jordansissel/fpm/issues/2048#issuecomment-1972196104).
RUN gem install ffi -v 1.16.3 \
    && gem install fpm -v ${FPM_VERSION} --minimal-deps --conservative --force \
    && gem uninstall ffi -v '>1.16.3' \
    && gem cleanup
