FROM docker.io/rockylinux/rockylinux:10.0.20250606-ubi

ARG GO_VERSION

ENV FPM_VERSION 1.15.1

# Temporary workaround for https://access.redhat.com/solutions/7134243:
# /lib64/librpm_sequoia.so.1: undefined symbol: EVP_PKEY_verify_message_init, version OPENSSL_3.4.0.
RUN dnf update -y rpm-sequoia openssl-libs \
    && dnf clean all

RUN dnf clean all \
    && dnf -y makecache --refresh \
    && dnf install -y \
        curl-minimal \
        gcc-c++ \
        git \
        make \
        rpm-build \
        ruby \
        ruby-devel \
        tar \
    && dnf clean all

RUN ARCHITECTURE=$(uname -m) \
    && case $ARCHITECTURE in \
            x86_64)  ARCHITECTURE='amd64' ;; \
            aarch64) ARCHITECTURE='arm64' ;; \
            *)       echo "unknown architecture: $ARCHITECTURE" && exit 1 ;; \
        esac \
    && curl -L -s curl -L -s https://go.dev/dl/go${GO_VERSION}.linux-${ARCHITECTURE}.tar.gz | tar xvfz - -C /usr/local

RUN gem install fpm -v ${FPM_VERSION} \
    && gem cleanup
