FROM docker.io/rockylinux/rockylinux:9.4.20240523-ubi

ARG GO_VERSION

RUN yum install -y \
        curl-minimal \
        gcc-c++ \
        git \
        make \
        rpm-build \
        ruby \
        ruby-devel \
        tar \
    && yum clean all

RUN ARCHITECTURE=$(uname -m) \
    && case $ARCHITECTURE in \
            x86_64)  ARCHITECTURE='amd64' ;; \
            aarch64) ARCHITECTURE='arm64' ;; \
            *)       echo "unknown architecture: $ARCHITECTURE" && exit 1 ;; \
        esac \
    && curl -L -s curl -L -s https://go.dev/dl/go${GO_VERSION}.linux-${ARCHITECTURE}.tar.gz | tar xvfz - -C /usr/local

RUN gem install fpm -v 1.15.1 \
    && gem cleanup
