name: Build

inputs:
  platform:
    required: true
  architecture:
    required: true
  go-version:
    required: true

runs:
  using: composite

  steps:
    # Using QEMU emulation is not needed now that ARM64 runners are available.
    # - uses: docker/setup-qemu-action@v3
    #   with:
    #     platforms: ${{ inputs.architecture }}

    - uses: docker/setup-buildx-action@v3

    - shell: bash
      run: |
        # XXX: for ARM64 builds, jobs occasionally fail with an error suggesting
        # that Docker is not ready. This is a dirty attempt to mitigate the
        # issue.
        if [ '${{ inputs.architecture }}' = 'arm64' ]; then
          for i in {1..10}; do
            if docker info > /dev/null 2>&1; then
              echo 'Docker is ready!'
              break
            else
              echo 'Waiting for Docker to be ready...'
              sleep 5
            fi
          done
        fi

        IMAGE=$( \
          docker build \
            --quiet \
            --platform linux/${{ inputs.architecture }} \
            --file extras/github/docker/Dockerfile-${{ inputs.platform }} \
            --build-arg GO_VERSION=${{ inputs.go-version }} \
            .)

        docker run \
          --rm \
          --platform linux/${{ inputs.architecture }} \
          --volume ${{ github.workspace }}:/workspace \
          --workdir /workspace \
          $IMAGE \
          bash -c ' \
            git config --global --add safe.directory /workspace; \
            export PATH=/usr/local/go/bin:$PATH; \
            export PLATFORM=${{ inputs.platform }}; \
            make lint vet test package'

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.platform }}-${{ inputs.architecture }}-artifacts
        path: |
          build/varnishmon-*.tgz
          build/varnishmon_*.deb
          build/varnishmon-*.rpm
        retention-days: 1
