// Code generated by mockery v2.52.1. DO NOT EDIT.

package workers

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockAPIHandler is an autogenerated mock type for the APIHandler type
type MockAPIHandler struct {
	mock.Mock
}

// ServeHTTP provides a mock function with given fields: w, r
func (_m *MockAPIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// Shutdown provides a mock function with no fields
func (_m *MockAPIHandler) Shutdown() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAPIHandler creates a new instance of MockAPIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIHandler {
	mock := &MockAPIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
