// Code generated by mockery v2.52.1. DO NOT EDIT.

package workers

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	fasthttp "github.com/valyala/fasthttp"
)

// MockAPIHandler is an autogenerated mock type for the APIHandler type
type MockAPIHandler struct {
	mock.Mock
}

// HandleRequest provides a mock function with given fields: ctx, rctx
func (_m *MockAPIHandler) HandleRequest(ctx context.Context, rctx *fasthttp.RequestCtx) {
	_m.Called(ctx, rctx)
}

// NewMockAPIHandler creates a new instance of MockAPIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIHandler {
	mock := &MockAPIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
